<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class RestaurantsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('restaurant')->insert([
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Ahmet Restoran',
                'description' => 'Açıklama',
                'address' => 'Adres',
                'phone' => '0555555555',
                'email' => 'ahmet@gmail.com',
                'capacity' => 10,
                'citiesID' => 1,
                'districtsID' => 6,
                'cuisine_type' => 'Kore Mutfağı',
                'view_type' => 'Deniz Manzarası',
                'categoryID' => 3,
                'image' => '/img/seederImages/is.jpg',
                'created_at' => Carbon::now()

            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Bektaş Restoran',
                'description' => 'Açıklama 2',
                'address' => 'Adres 2',
                'phone' => '06666666666',
                'email' => 'bektas@gmail.com',
                'capacity' => 5,
                'citiesID' => 1,
                'districtsID' => 1,
                'cuisine_type' => 'Kore Mutfağı',
                'view_type' => 'Deniz Manzarası',
                'categoryID' => 2,
                'image' => '/img/seederImages/kutlama.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Özlem Katip Restoran',
                'description' => 'Açıklama 3',
                'address' => 'Adres 3',
                'phone' => '01111111111',
                'email' => 'ozlem@gmail.com',
                'capacity' => 24,
                'citiesID' => 1,
                'districtsID' => 2,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Deniz Manzarası',
                'categoryID' => 2,
                'image' => '/img/seederImages/kutlama.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Ali Restoran',
                'description' => 'Açıklama 3',
                'address' => 'Adres 3',
                'phone' => '03333333333',
                'email' => 'ali@gmail.com',
                'capacity' => 5,
                'citiesID' => 1,
                'districtsID' => 6,
                'cuisine_type' => 'Japon Mutfağı',
                'view_type' => 'Tarihi Mekan',
                'categoryID' => 1,
                'image' => '/img/seederImages/ozel_gun.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Pınar Restoran',
                'description' => 'Açıklama 4',
                'address' => 'Adres 4',
                'phone' => '04444444444',
                'email' => 'pinar@gmail.com',
                'capacity' => 2,
                'citiesID' => 1,
                'districtsID' => 12,
                'cuisine_type' => 'İtalyan Mutfağı',
                'view_type' => 'Şehir Manzarası',
                'categoryID' => 4,
                'image' => '/img/seederImages/tek_kisi.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Sema Restoran',
                'description' => 'Açıklama 5',
                'address' => 'Adres 5',
                'phone' => '06666666666',
                'email' => 'sema@gmail.com',
                'capacity' => 3,
                'citiesID' => 1,
                'districtsID' => 1,
                'cuisine_type' => 'Meksika Mutfağı',
                'view_type' => 'Doğanın İçinde',
                'categoryID' => 4,
                'image' => '/img/seederImages/ozel_gun.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Furkan Restoran',
                'description' => 'Açıklama 6',
                'address' => 'Adres 6',
                'phone' => '08888888888',
                'email' => 'furkan@gmail.com',
                'capacity' => 8,
                'citiesID' => 1,
                'districtsID' => 12,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Deniz Manzarası',
                'categoryID' => 2,
                'image' => '/img/seederImages/alkol.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Tuğçe Restoran',
                'description' => 'Açıklama 7',
                'address' => 'Adres 7',
                'phone' => '07777777777',
                'email' => 'tugce@gmail.com',
                'capacity' => 14,
                'citiesID' => 1,
                'districtsID' => 6,
                'cuisine_type' => 'Japon Mutfağı',
                'view_type' => 'Tarihi Mekan',
                'categoryID' => 1,
                'image' => '/img/seederImages/balik.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Aylin Restoran',
                'description' => 'Açıklama 8',
                'address' => 'Adres 8',
                'phone' => '02222222222',
                'email' => 'aylin@gmail.com',
                'capacity' => 7,
                'citiesID' => 1,
                'districtsID' => 10,
                'cuisine_type' => 'Japon Mutfağı',
                'view_type' => 'Tarihi Mekan',
                'categoryID' => 1,
                'image' => '/img/seederImages/ozel_gun.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Aysun Restoran',
                'description' => 'Açıklama 9',
                'address' => 'Adres 9',
                'phone' => '03333333333',
                'email' => 'aysun@gmail.com',
                'capacity' => 11,
                'citiesID' => 1,
                'districtsID' => 8,
                'cuisine_type' => 'Japon Mutfağı',
                'view_type' => 'Şehir Manzarası',
                'categoryID' => 4,
                'image' => '/img/seederImages/tek_kisi.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Tuzla Balıkçısı',
                'description' => 'Açıklama 9',
                'address' => 'Tuzla',
                'phone' => '03333333333',
                'email' => 'balıkcı@gmail.com',
                'capacity' => 20,
                'citiesID' => 1,
                'districtsID' => 35,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Deniz Manzarası',
                'categoryID' => 4,
                'image' => '/img/seederImages/balik.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Jazz Coffee Tuzla',
                'description' => 'Açıklama 9',
                'address' => 'Tuzla',
                'phone' => '03333333333',
                'email' => 'jazzcoffee@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 35,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Deniz Manzarası',
                'categoryID' => 4,
                'image' => '/img/seederImages/balik.jpg',
                'created_at' => Carbon::now(),
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Mama Mia Restoran Tuzla',
                'description' => 'Açıklama 9',
                'address' => 'Tuzla',
                'phone' => '03333333333',
                'email' => 'mamamia@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 35,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Şehir Manzarası',
                'categoryID' => 4,
                'image' => '/img/seederImages/tek_kisi.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Ayaz Izgara Tuzla',
                'description' => 'Açıklama 9',
                'address' => 'Tuzla',
                'phone' => '03333333333',
                'email' => 'ayaz_ızgara@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 35,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Şehir Manzarası',
                'categoryID' => 4,
                'image' => '/img/seederImages/tek_kisi.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Legume Cafe & Bakery',
                'description' => 'Açıklama 9',
                'address' => 'Tuzla',
                'phone' => '03333333333',
                'email' => 'legume_cafe@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 35,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Şehir Manzarası',
                'categoryID' => 1,
                'image' => '/img/seederImages/ozel_gun.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'The North Shield',
                'description' => 'Açıklama 9',
                'address' => 'Tuzla',
                'phone' => '03333333333',
                'email' => 'north_shield@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 35,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Şehir Manzarası',
                'categoryID' => 2,
                'image' => '/img/seederImages/kutlama.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Zeytin Tuzla',
                'description' => 'Açıklama 9',
                'address' => 'Tuzla',
                'phone' => '03333333333',
                'email' => 'zeytintuzla@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 35,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Deniz Manzarası',
                'categoryID' => 2,
                'image' => '/img/seederImages/fastfood.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Kebap Tuzla',
                'description' => 'Açıklama 9',
                'address' => 'Tuzla',
                'phone' => '03333333333',
                'email' => 'kebaptuzla@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 35,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Deniz Manzarası',
                'categoryID' => 2,
                'image' => '/img/seederImages/fastfood.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Tiara Restoran Adalar',
                'description' => 'Açıklama 9',
                'address' => 'Adalar',
                'phone' => '03333333333',
                'email' => 'tiara@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 1,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Deniz Manzarası',
                'categoryID' => 2,
                'image' => '/img/seederImages/fastfood.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Mimoza Restoran Adalar',
                'description' => 'Açıklama 9',
                'address' => 'Adalar',
                'phone' => '03333333333',
                'email' => 'mimoza@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 1,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Deniz Manzarası',
                'categoryID' => 1,
                'image' => '/img/seederImages/ozel_gun.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Büyükada LocAda',
                'description' => 'Açıklama 9',
                'address' => 'Adalar',
                'phone' => '03333333333',
                'email' => 'büyükadalocada@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 1,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Deniz Manzarası',
                'categoryID' => 3,
                'image' => '/img/seederImages/is.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Heyamola Restoran Adalar',
                'description' => 'Açıklama 9',
                'address' => 'Adalar',
                'phone' => '03333333333',
                'email' => 'heyamola@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 1,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Deniz Manzarası',
                'categoryID' => 4,
                'image' => '/img/seederImages/tek_kisi.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Kutlama Restoran Adalar',
                'description' => 'Açıklama 9',
                'address' => 'Adalar',
                'phone' => '03333333333',
                'email' => 'kutlamarestoran@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 1,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Deniz Manzarası',
                'categoryID' => 2,
                'image' => '/img/seederImages/kutlama.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Palya Restoran Adalar',
                'description' => 'Açıklama 9',
                'address' => 'Adalar',
                'phone' => '03333333333',
                'email' => 'palyarestoran@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 1,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Deniz Manzarası',
                'categoryID' => 2,
                'image' => '/img/seederImages/kutlama.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Mira Balık Arnavutköy',
                'description' => 'Açıklama 9',
                'address' => 'Arnavutköy',
                'phone' => '03333333333',
                'email' => 'mirabalık@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 2,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Deniz Manzarası',
                'categoryID' => 2,
                'image' => '/img/seederImages/kutlama.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Doğa Kır Lokantası ',
                'description' => 'Açıklama 9',
                'address' => 'Arnavutköy',
                'phone' => '03333333333',
                'email' => 'dogakir@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 2,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Deniz Manzarası',
                'categoryID' => 2,
                'image' => '/img/seederImages/kutlama.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Coni&Co Restoran ',
                'description' => 'Açıklama 9',
                'address' => 'Arnavutköy',
                'phone' => '03333333333',
                'email' => 'coni@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 2,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Deniz Manzarası',
                'categoryID' => 1,
                'image' => '/img/seederImages/ozel_gun.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Madre Arnavutköy',
                'description' => 'Açıklama 9',
                'address' => 'Arnavutköy',
                'phone' => '03333333333',
                'email' => 'madre@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 2,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Şehir Manzarası',
                'categoryID' => 3,
                'image' => '/img/seederImages/is.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Bi-Resto Arnavutköy',
                'description' => 'Açıklama 9',
                'address' => 'Arnavutköy',
                'phone' => '03333333333',
                'email' => 'biresto@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 2,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Deniz Manzarası',
                'categoryID' => 4,
                'image' => '/img/seederImages/tek_kisi.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Antica Lokantası Arnavutköy',
                'description' => 'Açıklama 9',
                'address' => 'Arnavutköy',
                'phone' => '03333333333',
                'email' => 'antica@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 2,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Şehir Manzarası',
                'categoryID' => 2,
                'image' => '/img/seederImages/kutlama.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Nokta Tesisleri Arnavutköy',
                'description' => 'Açıklama 9',
                'address' => 'Arnavutköy',
                'phone' => '03333333333',
                'email' => 'nokta@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 2,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Doğanın İçinde',
                'categoryID' => 1,
                'image' => '/img/seederImages/ozel_gun.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Foça Restoran Ataşehir',
                'description' => 'Açıklama 9',
                'address' => 'Ataşehir',
                'phone' => '03333333333',
                'email' => 'foca@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 3,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Doğanın İçinde',
                'categoryID' => 1,
                'image' => '/img/seederImages/ozel_gun.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Süslü Konak',
                'description' => 'Açıklama 9',
                'address' => 'Ataşehir',
                'phone' => '03333333333',
                'email' => 'süslü@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 3,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Şehir Manzarası',
                'categoryID' => 2,
                'image' => '/img/seederImages/kutlama.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Quick Burger Ataşehir',
                'description' => 'Açıklama 9',
                'address' => 'Ataşehir',
                'phone' => '03333333333',
                'email' => 'quick_burger@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 3,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Şehir Manzarası',
                'categoryID' => 4,
                'image' => '/img/seederImages/tek_kisi.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Divan Pub Ataşehir',
                'description' => 'Açıklama 9',
                'address' => 'Ataşehir',
                'phone' => '03333333333',
                'email' => 'divan@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 3,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Şehir Manzarası',
                'categoryID' => 1,
                'image' => '/img/seederImages/ozel_gun.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Çeşme Alaçatı Balıkçısı ',
                'description' => 'Açıklama 9',
                'address' => 'Ataşehir',
                'phone' => '03333333333',
                'email' => 'cesme@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 3,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Deniz Manzarası',
                'categoryID' => 4,
                'image' => '/img/seederImages/tek_kisi.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Develi Restoran Ataşehir',
                'description' => 'Açıklama 9',
                'address' => 'Ataşehir',
                'phone' => '03333333333',
                'email' => 'develi@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 3,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Deniz Manzarası',
                'categoryID' => 2,
                'image' => '/img/seederImages/kutlama.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Sanat Ocakbaşı Ataşehir',
                'description' => 'Açıklama 9',
                'address' => 'Ataşehir',
                'phone' => '03333333333',
                'email' => 'sanat@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 3,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Doğanın İçinde',
                'categoryID' => 3,
                'image' => '/img/seederImages/is.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Veganista Ataşehir',
                'description' => 'Açıklama 9',
                'address' => 'Ataşehir',
                'phone' => '03333333333',
                'email' => 'veganista@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 3,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Doğanın İçinde',
                'categoryID' => 4,
                'image' => '/img/seederImages/tek_kisi.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Grill Prime Ataşehir',
                'description' => 'Açıklama 9',
                'address' => 'Ataşehir',
                'phone' => '03333333333',
                'email' => 'grill@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 3,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Doğanın İçinde',
                'categoryID' => 1,
                'image' => '/img/seederImages/ozel_gun.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Baler Garden',
                'description' => 'Her davete uygun, şıklık ve lezzetin buluşma noktası',
                'address' => 'Avcılar',
                'phone' => '03233333334',
                'email' => 'baler@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 4,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Deniz Manzarası',
                'categoryID' => 2,
                'image' => '/img/seederImages/ozel_gun.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Big Mammas Avcılar',
                'description' => 'Lezzetin ve dostane atmosferin buluştuğu, her anı özel kılan bir deneyim',
                'address' => 'Avcılar',
                'phone' => '01233333334',
                'email' => 'bigmamas@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 4,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Şehir Manzarası',
                'categoryID' => 1,
                'image' => '/img/seederImages/fastfood.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'İskele Restoran',
                'description' => 'Denizden sofraya taptaze balıklar, eşsiz tatlar ve samimi bir atmosfer',
                'address' => 'Avcılar',
                'phone' => '01133333334',
                'email' => 'iskele@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 4,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Deniz Manzarası',
                'categoryID' => 4,
                'image' => '/img/seederImages/balik.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => ' Etçi Mehmet SteakHouse',
                'description' => 'Denizden sofraya taptaze balıklar, eşsiz tatlar ve samimi bir atmosfer',
                'address' => 'Avcılar',
                'phone' => '01131333334',
                'email' => 'etci_mehmet@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 4,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Doğanın İçinde',
                'categoryID' => 3,
                'image' => '/img/seederImages/et.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => ' Pandora Cafe&Restoran',
                'description' => 'Lezzetli yemekler, keyifli sohbetler ve sıcak bir atmosferin buluşma noktası',
                'address' => 'Bağcılar',
                'phone' => '01231313334',
                'email' => 'pandora@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 5,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Doğanın İçinde',
                'categoryID' => 3,
                'image' => '/img/seederImages/ozel_gun.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Cihan Derya Balık',
                'description' => 'Lezzetli yemekler, keyifli sohbetler ve sıcak bir atmosferin buluşma noktası',
                'address' => 'Bağcılar',
                'phone' => '01231313334',
                'email' => 'cihan@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 5,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Deniz Manzarası',
                'categoryID' => 3,
                'image' => '/img/seederImages/ozel_gun.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Miraç Et Mangal',
                'description' => 'Lezzetli yemekler, keyifli sohbetler ve sıcak bir atmosferin buluşma noktası',
                'address' => 'Bağcılar',
                'phone' => '01281313334',
                'email' => 'mirac@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 5,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Şehir Manzarası',
                'categoryID' => 4,
                'image' => '/img/seederImages/et.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Seraf Restoran',
                'description' => 'Lezzetli yemekler, keyifli sohbetler ve sıcak bir atmosferin buluşma noktası',
                'address' => 'Bağcılar',
                'phone' => '01291313334',
                'email' => 'seraf@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 5,
                'cuisine_type' => 'İtalyan Mutfağı',
                'view_type' => 'Doğanın İçinde',
                'categoryID' => 3,
                'image' => '/img/seederImages/alkol.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Karadeniz Balıkçısı',
                'description' => 'Lezzetli yemekler, keyifli sohbetler ve sıcak bir atmosferin buluşma noktası',
                'address' => 'Bahçelievler',
                'phone' => '01291813334',
                'email' => 'karadeniz_balık@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 6,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Deniz Manzarası',
                'categoryID' => 4,
                'image' => '/img/seederImages/balik.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Tarihi Sebat Lokantası',
                'description' => 'Lezzetli yemekler, keyifli sohbetler ve sıcak bir atmosferin buluşma noktası',
                'address' => 'Bahçelievler',
                'phone' => '01291893334',
                'email' => 'tarihi_sebat@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 6,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Tarihi Mekan',
                'categoryID' => 3,
                'image' => '/img/seederImages/et.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Veganarsist',
                'description' => 'Lezzetli yemekler, keyifli sohbetler ve sıcak bir atmosferin buluşma noktası',
                'address' => 'Bahçelievler',
                'phone' => '01291813335',
                'email' => 'veganarsist@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 6,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Şehir Manzarası',
                'categoryID' => 4,
                'image' => '/img/seederImages/vegan.png',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Fenerbahçe Balıkçısı',
                'description' => 'Lezzetli yemekler, keyifli sohbetler ve sıcak bir atmosferin buluşma noktası',
                'address' => 'Bakırköy',
                'phone' => '01291818435',
                'email' => 'fener_balık@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 7,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Deniz Manzarası',
                'categoryID' => 3,
                'image' => '/img/seederImages/balik.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Yelken Restoran',
                'description' => 'Lezzetli yemekler, keyifli sohbetler ve sıcak bir atmosferin buluşma noktası',
                'address' => 'Bakırköy',
                'phone' => '01291818485',
                'email' => 'yelken@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 7,
                'cuisine_type' => 'Meksika Mutfağı',
                'view_type' => 'Şehir Manzarası',
                'categoryID' => 1,
                'image' => '/img/seederImages/is.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Hanedan Mangalbası',
                'description' => 'Lezzetli yemekler, keyifli sohbetler ve sıcak bir atmosferin buluşma noktası',
                'address' => 'Bakırköy',
                'phone' => '01291818485',
                'email' => 'hanedan_mangalbas@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 7,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Doğanın İçinde',
                'categoryID' => 4,
                'image' => '/img/seederImages/et.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Göl Balık Restoranı',
                'description' => 'Lezzetli yemekler, keyifli sohbetler ve sıcak bir atmosferin buluşma noktası',
                'address' => 'Başakşehir',
                'phone' => '01291818485',
                'email' => 'gol_balık@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 8,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Deniz Manzarası',
                'categoryID' => 3,
                'image' => '/img/seederImages/balik.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Vegan İstanbul',
                'description' => 'Lezzetli yemekler, keyifli sohbetler ve sıcak bir atmosferin buluşma noktası',
                'address' => 'Başakşehir',
                'phone' => '01292818485',
                'email' => 'vegan_ist@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 8,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Şehir Manzarası',
                'categoryID' => 4,
                'image' => '/img/seederImages/vegan.png',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Seventeen Pizza',
                'description' => 'Lezzetli yemekler, keyifli sohbetler ve sıcak bir atmosferin buluşma noktası',
                'address' => 'Başakşehir',
                'phone' => '01291813485',
                'email' => 'seventeen@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 8,
                'cuisine_type' => 'İtalyan Mutfağı',
                'view_type' => 'Doğanın İçinde',
                'categoryID' => 2,
                'image' => '/img/seederImages/dunya_mutfagi.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Ercan SteakHouse',
                'description' => 'Lezzetli yemekler, keyifli sohbetler ve sıcak bir atmosferin buluşma noktası',
                'address' => 'Başakşehir',
                'phone' => '01291813495',
                'email' => 'ercan_steak@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 8,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Şehir Manzarası',
                'categoryID' => 1,
                'image' => '/img/seederImages/is.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Nusr-Et SteakHouse',
                'description' => 'Lezzetli yemekler, keyifli sohbetler ve sıcak bir atmosferin buluşma noktası',
                'address' => 'Bayrampaşa',
                'phone' => '01291814495',
                'email' => 'nusr_et@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 9,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Şehir Manzarası',
                'categoryID' => 1,
                'image' => '/img/seederImages/et.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Plant Burger',
                'description' => 'Lezzetli yemekler, keyifli sohbetler ve sıcak bir atmosferin buluşma noktası',
                'address' => 'Bayrampaşa',
                'phone' => '01291814495',
                'email' => 'plant_burger@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 9,
                'cuisine_type' => 'İtalyan Mutfağı',
                'view_type' => 'Deniz Manzarası',
                'categoryID' => 4,
                'image' => '/img/seederImages/fastfood.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Korean House',
                'description' => 'Lezzetli yemekler, keyifli sohbetler ve sıcak bir atmosferin buluşma noktası',
                'address' => 'Bayrampaşa',
                'phone' => '01292815495',
                'email' => 'korean_house@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 9,
                'cuisine_type' => 'Kore Mutfağı',
                'view_type' => 'Doğanın İçinde',
                'categoryID' => 1,
                'image' => '/img/seederImages/dunya_mutfagi.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Akin Balık',
                'description' => 'Lezzetli yemekler, keyifli sohbetler ve sıcak bir atmosferin buluşma noktası',
                'address' => 'Bayrampaşa',
                'phone' => '03292815495',
                'email' => 'akin_balik@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 9,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Deniz Manzarası',
                'categoryID' => 4,
                'image' => '/img/seederImages/balik.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Taç Balık Restaurant',
                'description' => 'Lezzetli yemekler, keyifli sohbetler ve sıcak bir atmosferin buluşma noktası',
                'address' => 'Beykoz',
                'phone' => '07292815495',
                'email' => 'tac_balik@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 10,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Şehir Manzarası',
                'categoryID' => 4,
                'image' => '/img/seederImages/balik.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Boğaziçi Yakamoz',
                'description' => 'Lezzetli yemekler, keyifli sohbetler ve sıcak bir atmosferin buluşma noktası',
                'address' => 'Beykoz',
                'phone' => '03292815495',
                'email' => 'bozgazici_yakamoz@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 10,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Deniz Manzarası',
                'categoryID' => 3,
                'image' => '/img/seederImages/ozel_gun.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Çam Vadisi',
                'description' => 'Lezzetli yemekler, keyifli sohbetler ve sıcak bir atmosferin buluşma noktası',
                'address' => 'Beykoz',
                'phone' => '03292812495',
                'email' => 'cam_vadisi@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 10,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Doğanın İçinde',
                'categoryID' => 4,
                'image' => '/img/seederImages/et.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Lotus Coffee & Resto',
                'description' => 'Lezzetli yemekler, keyifli sohbetler ve sıcak bir atmosferin buluşma noktası',
                'address' => 'Beykoz',
                'phone' => '03292111495',
                'email' => 'lotus_coffee@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 10,
                'cuisine_type' => 'Meksika Mutfağı',
                'view_type' => 'Şehir Manzarası',
                'categoryID' => 4,
                'image' => '/img/seederImages/dunya_mutfagi.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Veggie Vokkie',
                'description' => 'Lezzetli yemekler, keyifli sohbetler ve sıcak bir atmosferin buluşma noktası',
                'address' => 'Beylikdüzü',
                'phone' => '03292112495',
                'email' => 'veggie@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 11,
                'cuisine_type' => 'Meksika Mutfağı',
                'view_type' => 'Şehir Manzarası',
                'categoryID' => 4,
                'image' => '/img/seederImages/vegan.png',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Calisto Balık',
                'description' => 'Lezzetli yemekler, keyifli sohbetler ve sıcak bir atmosferin buluşma noktası',
                'address' => 'Beylikdüzü',
                'phone' => '03292111495',
                'email' => 'calisto@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 11,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Deniz Manzarası',
                'categoryID' => 4,
                'image' => '/img/seederImages/balik.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Zeyn Steakhouse & Kebap',
                'description' => 'Lezzetli yemekler, keyifli sohbetler ve sıcak bir atmosferin buluşma noktası',
                'address' => 'Beylikdüzü',
                'phone' => '03292111191',
                'email' => 'zeyn_et@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 11,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Şehir Manzarası',
                'categoryID' => 2,
                'image' => '/img/seederImages/et.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Poyraz Sahil Balık',
                'description' => 'Lezzetli yemekler, keyifli sohbetler ve sıcak bir atmosferin buluşma noktası',
                'address' => 'Beyoğlu',
                'phone' => '03292111492',
                'email' => 'poyraz@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 12,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'DenizManzarası',
                'categoryID' => 2,
                'image' => '/img/seederImages/balik.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 3,
                'name' => 'Kasabım Ethane',
                'description' => 'Lezzetli yemekler, keyifli sohbetler ve sıcak bir atmosferin buluşma noktası',
                'address' => 'Beyoğlu',
                'phone' => '03293111431',
                'email' => 'kasabım_ethane@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 12,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Şehir Manzarası',
                'categoryID' => 3,
                'image' => '/img/seederImages/et.jpg',
                'created_at' => Carbon::now()
            ],
            [
                'guid' => Str::uuid()->toString(),
                'userID' => 4,
                'name' => 'Litera Restoran',
                'description' => 'Lezzetli yemekler, keyifli sohbetler ve sıcak bir atmosferin buluşma noktası',
                'address' => 'Beyoğlu',
                'phone' => '01292111591',
                'email' => 'litera@gmail.com',
                'capacity' => 35,
                'citiesID' => 1,
                'districtsID' => 12,
                'cuisine_type' => 'Türk Mutfağı',
                'view_type' => 'Şehir Manzarası',
                'categoryID' => 2,
                'image' => '/img/seederImages/kutlama.jpg',
                'created_at' => Carbon::now()
            ],
        ]);
    }
}
